Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "master",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.1.20",
          :ssh_port => '2200'
        },
        {
          :hostname => "test-node",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.1.19",
          :ssh_port => '2219'
        },
        {
          :hostname => "dev-node",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.1.18",
          :ssh_port => '2218'
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 512]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end
        end
    end
end
